[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect API routes to Netlify Functions
[[redirects]]
  from = "/api/instagram/status"
  to = "/.netlify/functions/instagram-status"
  status = 200

[[redirects]]
  from = "/api/stories/generate"
  to = "/.netlify/functions/stories-generate-svg"
  status = 200

[[redirects]]
  from = "/api/stories-generate-svg"
  to = "/.netlify/functions/stories-generate-svg"
  status = 200

[[redirects]]
  from = "/api/instagram-status"
  to = "/.netlify/functions/instagram-status"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "client/netlify/functions"
